analytics:
  google:
    id: UA-100402621-1

repository: iROCKBUNNY/N-Back
repository_url: https://github.com/iROCKBUNNY/N-Back

timezone: Asia/Shanghai

name: N-Back
author: iROCKBUNNY
author_url: http://irockbunny.com
organization: iROCKBUNNY Lab
organization_url: http://irockbunnylab.net
description: A JavaScript Implementation of the N-Back Task
keywords: N-Back, The N-Back Task, Game
url: http://n-back.irockbunnylab.com
contact: contact[at]irockbunny[dot]com

logo: /images/logo.png
logo_0: /images/logo-0.png
logo_1: /images/logo-1.png
logo_2: /images/logo-2.png

gems:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor