analytics:
  google:
    id: UA-100402621-1

repository: iRB-Lab/N-Back
repository_url: https://github.com/iRB-Lab/N-Back

timezone: Asia/Shanghai

title: N-Back
description: A JavaScript Implementation of the N-Back Task
keywords: N-Back, The N-Back Task, Game
url: http://n-back.irockbunnylab.com

author: iROCKBUNNY
author_url: http://irockbunny.com
organization: iROCKBUNNY Lab
organization_url: http://irockbunnylab.net

contact: contact[at]irockbunny[dot]com

image: /images/logo.png
logo: /images/logo.png
logo_0: /images/logo-0.png
logo_1: /images/logo-1.png
logo_2: /images/logo-2.png

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor